"use client";

import * as React from "react";
import Link from "next/link";
import {
  Calendar,
  FileText,
  Pill,
} from "lucide-react";

import { useMiniAppAuth } from "./miniapp-auth-provider";
import { useT } from "./mini-i18n";
import { useActiveContext } from "../_hooks/use-active-context";
import { useMedications } from "../_hooks/use-medications";
import { MCard, MSpinner, formatTimeISO } from "./mini-ui";
import { MA_ACCENTS } from "./mini-app-tokens";
import { HomeHero } from "./home-hero";
import { ClinicInfoCard } from "./clinic-info-card";
import { InboxBanner } from "./inbox-banner";
import { LanguagePickerScreen } from "./language-picker-screen";
import { TreatmentPlanCard } from "./treatment-plan-card";
import { useTelegramWebApp } from "@/hooks/use-telegram-webapp";
import { OpenInTelegramFallback } from "./open-in-telegram-fallback";

export function MiniAppHome() {
  const { state, clinicSlug } = useMiniAppAuth();
  const { setBackButton } = useTelegramWebApp();
  const t = useT();

  React.useEffect(() => {
    // No back button on home.
    return setBackButton(undefined);
  }, [setBackButton]);

  if (state.status === "loading") return <MSpinner label={t.common.loading} />;
  if (state.status === "no_tg") return <OpenInTelegramFallback />;
  if (state.status === "error") {
    return (
      <MCard>
        <p className="text-sm font-medium">{t.common.error}</p>
        <p className="mt-1 text-xs" style={{ color: "var(--tg-hint)" }}>
          {state.message}
        </p>
      </MCard>
    );
  }

  // First-run language picker: if name is a TG-autogenerated placeholder,
  // the user hasn't customized — but language was copied from TG locale, so
  // we only force the picker when the Telegram language_code wasn't ru/uz.
  // Simple heuristic: if preferredLang isn't set yet (we always set it to
  // RU/UZ on auth), skip. Otherwise no picker.
  if (state.patient.preferredLang !== "RU" && state.patient.preferredLang !== "UZ") {
    return <LanguagePickerScreen />;
  }

  return <HomeContent slug={clinicSlug} />;
}

function greetingTemplate(t: ReturnType<typeof useT>, hour: number): string {
  if (hour >= 5 && hour < 11) return t.home.greetingMorning;
  if (hour >= 11 && hour < 17) return t.home.greetingDay;
  if (hour >= 17 && hour < 23) return t.home.greetingEvening;
  return t.home.greetingNight;
}

function formatShortDate(iso: string, lang: "RU" | "UZ"): string {
  return new Date(iso).toLocaleDateString(
    lang === "UZ" ? "uz-Latn-UZ" : "ru-RU",
    { day: "2-digit", month: "2-digit" },
  );
}

function BentoTile({
  href,
  title,
  hint,
  icon: Icon,
  color,
  tall,
  wide,
  delay,
  animate,
}: {
  href: string;
  title: string;
  hint?: string | null;
  icon: React.ComponentType<{ className?: string }>;
  color: string;
  tall?: boolean;
  wide?: boolean;
  delay?: number;
  animate?: boolean;
}) {
  const tg = useTelegramWebApp();
  return (
    <Link
      href={href}
      onClick={() => tg.haptic.selection()}
      className={`${animate ? "ma-fade-up " : ""}${wide ? "col-span-2 " : ""}${
        tall
          ? "flex min-h-[116px] flex-col justify-between"
          : "flex min-h-[64px] flex-row items-center gap-3"
      } rounded-2xl p-4 text-left ma-press active:scale-[0.98]`}
      style={{
        backgroundColor: "var(--tg-section-bg)",
        color: "var(--tg-text)",
        boxShadow: "var(--ma-card-shadow, 0 1px 2px rgba(0,0,0,0.04))",
        animationDelay: animate && delay != null ? `${delay}ms` : undefined,
      }}
    >
      <span
        className={`grid shrink-0 place-items-center rounded-full ${
          tall ? "h-9 w-9" : "h-8 w-8"
        }`}
        style={{
          backgroundColor: `color-mix(in oklch, ${color} 14%, transparent)`,
          color,
        }}
      >
        <Icon className={tall ? "h-5 w-5" : "h-4 w-4"} />
      </span>
      <span className={tall ? "" : "min-w-0 flex-1"}>
        <span className="block text-[15px] font-semibold leading-tight">
          {title}
        </span>
        {hint ? (
          <span
            className="mt-0.5 block truncate text-xs"
            style={{ color: "var(--tg-hint)" }}
          >
            {hint}
          </span>
        ) : null}
      </span>
    </Link>
  );
}

function HomeContent({ slug }: { slug: string }) {
  const t = useT();
  const { state } = useMiniAppAuth();
  const { onBehalfOf } = useActiveContext();
  const meds = useMedications(onBehalfOf);
  const tg = useTelegramWebApp();
  const patient = state.status === "ready" ? state.patient : null;
  const firstName = patient?.fullName?.split(" ")[0] ?? "";
  const lang = patient?.preferredLang ?? "RU";
  // Frozen per mount — react-hooks/purity forbids Date.now() in render; the
  // greeting doesn't need to flip while the screen is open.
  const [now] = React.useState(() => Date.now());

  // The entrance stagger plays once per session — re-mounting home on every
  // back-navigation used to replay the full second of fade-ups, which made
  // the app feel slower than it is. HomeContent only mounts client-side
  // (auth state starts as "loading"), so sessionStorage is safe to read in
  // the initializer.
  const [animate] = React.useState(() => {
    try {
      return sessionStorage.getItem("ma:introPlayed") !== "1";
    } catch {
      return false;
    }
  });
  React.useEffect(() => {
    try {
      sessionStorage.setItem("ma:introPlayed", "1");
    } catch {
      /* ignore */
    }
  }, []);

  // Bento previews — data inside navigation (П12).
  const nextDose = React.useMemo(() => {
    const list = meds.data?.prescriptions ?? [];
    const candidates = list
      .filter((p) => p.status === "ACTIVE" && p.nextDoseAt)
      .map((p) => p.nextDoseAt!)
      .sort();
    return candidates[0] ?? null;
  }, [meds.data]);
  const medsHint = meds.data
    ? nextDose
      ? new Date(nextDose).getDate() === new Date(now).getDate()
        ? t.home.bento.medsNext.replace(
            "{time}",
            formatTimeISO(nextDose),
          )
        : t.home.bento.medsNextDate.replace(
            "{date}",
            formatShortDate(nextDose, lang),
          )
      : t.home.bento.medsNone
    : null;

  return (
    <>
      <div
        className={`${animate ? "ma-fade-up " : ""}mb-5`}
        style={animate ? { animationDelay: "0ms" } : undefined}
      >
        <h1 className="text-2xl font-bold leading-tight">
          {greetingTemplate(t, new Date(now).getHours()).replace(
            "{name}",
            firstName,
          )}
        </h1>
        <p className="mt-1 text-sm" style={{ color: "var(--tg-hint)" }}>
          {t.home.subtitle}
        </p>
      </div>
      <HomeHero slug={slug} animate={animate} />
      <Link
        href={`/c/${slug}/my/book/service`}
        onClick={() => tg.haptic.selection()}
        className={`${animate ? "ma-fade-up " : ""}mb-5 flex min-h-[52px] items-center justify-center gap-2 rounded-2xl px-4 py-3 text-base font-semibold text-white ma-press active:scale-[0.98]`}
        style={{
          backgroundColor: "var(--tg-accent)",
          boxShadow:
            "0 6px 16px color-mix(in oklch, var(--tg-accent) 35%, transparent)",
          animationDelay: animate ? "80ms" : undefined,
        }}
      >
        <Calendar className="h-5 w-5" />
        {t.home.ctaBook}
      </Link>
      <InboxBanner />
      <TreatmentPlanCard slug={slug} animate={animate} />
      <div className="grid grid-cols-2 gap-3">
        <BentoTile
          href={`/c/${slug}/my/medications`}
          title={t.home.bento.meds}
          hint={medsHint}
          icon={Pill}
          color={MA_ACCENTS.warning}
          tall
          delay={120}
          animate={animate}
        />
        <BentoTile
          href={`/c/${slug}/my/documents`}
          title={t.home.bento.docs}
          hint={t.home.bento.docsHint}
          icon={FileText}
          color="var(--tg-accent)"
          tall
          delay={160}
          animate={animate}
        />
      </div>
      <div className="mt-5">
        <ClinicInfoCard slug={slug} animate={animate} />
      </div>
    </>
  );
}
