"use client";

import * as React from "react";
import Link from "next/link";
import { Calendar, FileText, History, User } from "lucide-react";

import { useMiniAppAuth } from "./miniapp-auth-provider";
import { useT } from "./mini-i18n";
import { useAppointments } from "../_hooks/use-appointments";
import {
  MCard,
  MEmpty,
  MSection,
  MSpinner,
  formatDateISO,
  formatTimeISO,
} from "./mini-ui";
import { LanguagePickerScreen } from "./language-picker-screen";
import { useTelegramWebApp } from "@/hooks/use-telegram-webapp";
import { OpenInTelegramFallback } from "./open-in-telegram-fallback";

function CtaTile({
  href,
  label,
  icon: Icon,
  delay,
}: {
  href: string;
  label: string;
  icon: React.ComponentType<{ className?: string }>;
  delay?: number;
}) {
  return (
    <Link
      href={href}
      className="ma-fade-up flex min-h-[112px] flex-col justify-between rounded-2xl p-4 text-left transition active:scale-[0.98]"
      style={{
        backgroundColor: "var(--tg-section-bg)",
        color: "var(--tg-text)",
        animationDelay: delay != null ? `${delay}ms` : undefined,
        boxShadow: "0 1px 2px rgba(0,0,0,0.04)",
      }}
    >
      <span style={{ color: "var(--tg-accent)" }}>
        <Icon className="h-6 w-6" />
      </span>
      <span className="text-base font-semibold leading-tight">{label}</span>
    </Link>
  );
}

export function MiniAppHome() {
  const { state, clinicSlug } = useMiniAppAuth();
  const { setBackButton } = useTelegramWebApp();
  const t = useT();

  React.useEffect(() => {
    // No back button on home.
    return setBackButton(undefined);
  }, [setBackButton]);

  if (state.status === "loading") return <MSpinner label={t.common.loading} />;
  if (state.status === "no_tg") return <OpenInTelegramFallback />;
  if (state.status === "error") {
    return (
      <MCard>
        <p className="text-sm font-medium">{t.common.error}</p>
        <p className="mt-1 text-xs" style={{ color: "var(--tg-hint)" }}>
          {state.message}
        </p>
      </MCard>
    );
  }

  // First-run language picker: if name is a TG-autogenerated placeholder,
  // the user hasn't customized — but language was copied from TG locale, so
  // we only force the picker when the Telegram language_code wasn't ru/uz.
  // Simple heuristic: if preferredLang isn't set yet (we always set it to
  // RU/UZ on auth), skip. Otherwise no picker.
  if (state.patient.preferredLang !== "RU" && state.patient.preferredLang !== "UZ") {
    return <LanguagePickerScreen />;
  }

  return <HomeContent slug={clinicSlug} />;
}

function HomeContent({ slug }: { slug: string }) {
  const t = useT();
  const { state } = useMiniAppAuth();
  const upcoming = useAppointments("upcoming");
  const patient = state.status === "ready" ? state.patient : null;
  const firstName = patient?.fullName?.split(" ")[0] ?? "";
  const lang = patient?.preferredLang ?? "RU";

  return (
    <>
      <div className="ma-fade-up mb-5" style={{ animationDelay: "0ms" }}>
        <h1 className="text-2xl font-bold leading-tight">
          {t.home.greeting.replace("{name}", firstName)}
        </h1>
        <p className="mt-1 text-sm" style={{ color: "var(--tg-hint)" }}>
          {t.home.subtitle}
        </p>
      </div>
      <div className="ma-fade-up" style={{ animationDelay: "60ms" }}>
        <MSection title={t.home.upcomingHeader}>
          {upcoming.isLoading ? (
            <MSpinner />
          ) : upcoming.data && upcoming.data.length > 0 ? (
            <MCard>
              <div className="flex items-start justify-between gap-3">
                <div className="min-w-0">
                  <div className="text-base font-semibold">
                    {lang === "UZ"
                      ? upcoming.data[0].doctor.nameUz
                      : upcoming.data[0].doctor.nameRu}
                  </div>
                  <div
                    className="mt-0.5 text-xs"
                    style={{ color: "var(--tg-hint)" }}
                  >
                    {lang === "UZ"
                      ? upcoming.data[0].doctor.specializationUz
                      : upcoming.data[0].doctor.specializationRu}
                  </div>
                </div>
                <div className="shrink-0 text-right">
                  <div className="text-sm font-semibold">
                    {formatDateISO(upcoming.data[0].date, lang)}
                  </div>
                  <div className="text-xs" style={{ color: "var(--tg-accent)" }}>
                    {upcoming.data[0].time ?? formatTimeISO(upcoming.data[0].date)}
                  </div>
                </div>
              </div>
            </MCard>
          ) : (
            <MEmpty>{t.home.noUpcoming}</MEmpty>
          )}
        </MSection>
      </div>
      <div className="grid grid-cols-2 gap-3">
        <CtaTile
          href={`/c/${slug}/my/book/service`}
          label={t.home.ctaBook}
          icon={Calendar}
          delay={120}
        />
        <CtaTile
          href={`/c/${slug}/my/appointments`}
          label={t.home.ctaMyAppointments}
          icon={History}
          delay={170}
        />
        <CtaTile
          href={`/c/${slug}/my/documents`}
          label={t.home.ctaDocuments}
          icon={FileText}
          delay={220}
        />
        <CtaTile
          href={`/c/${slug}/my/profile`}
          label={t.home.ctaProfile}
          icon={User}
          delay={270}
        />
      </div>
    </>
  );
}
