-- Phase 9a — Branches schema + backfill.
--
-- Stage A (auto-generated by `prisma migrate dev --create-only`):
--   - CREATE TABLE "Branch"
--   - ADD COLUMN "branchId" (NULLABLE) on Doctor, Cabinet, Appointment,
--     DoctorSchedule, DoctorTimeOff
--   - FK + indexes
--
-- Stage B (hand-appended below):
--   - For every existing Clinic, create a default Branch (slug='hq',
--     isDefault=true). Idempotent via the unique (clinicId, slug) index.
--   - Backfill `branchId` on the 5 newly-extended tables to the clinic's
--     default branch.
--
-- branchId stays NULLABLE in this migration so a prod rollout can backfill
-- at its own pace; Phase 9b tightens to NOT NULL after every existing row
-- has been reconciled.

-- AlterTable
ALTER TABLE "Appointment" ADD COLUMN     "branchId" TEXT;

-- AlterTable
ALTER TABLE "Cabinet" ADD COLUMN     "branchId" TEXT;

-- AlterTable
ALTER TABLE "Doctor" ADD COLUMN     "branchId" TEXT;

-- AlterTable
ALTER TABLE "DoctorSchedule" ADD COLUMN     "branchId" TEXT;

-- AlterTable
ALTER TABLE "DoctorTimeOff" ADD COLUMN     "branchId" TEXT;

-- CreateTable
CREATE TABLE "Branch" (
    "id" TEXT NOT NULL,
    "clinicId" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "nameRu" TEXT NOT NULL,
    "nameUz" TEXT NOT NULL,
    "address" TEXT,
    "phone" TEXT,
    "timezone" TEXT,
    "isDefault" BOOLEAN NOT NULL DEFAULT false,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Branch_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Branch_clinicId_isActive_idx" ON "Branch"("clinicId", "isActive");

-- CreateIndex
CREATE UNIQUE INDEX "Branch_clinicId_slug_key" ON "Branch"("clinicId", "slug");

-- CreateIndex
CREATE INDEX "Appointment_clinicId_branchId_idx" ON "Appointment"("clinicId", "branchId");

-- CreateIndex
CREATE INDEX "Cabinet_clinicId_branchId_idx" ON "Cabinet"("clinicId", "branchId");

-- CreateIndex
CREATE INDEX "Doctor_clinicId_branchId_idx" ON "Doctor"("clinicId", "branchId");

-- CreateIndex
CREATE INDEX "DoctorSchedule_clinicId_branchId_idx" ON "DoctorSchedule"("clinicId", "branchId");

-- CreateIndex
CREATE INDEX "DoctorTimeOff_clinicId_branchId_idx" ON "DoctorTimeOff"("clinicId", "branchId");

-- AddForeignKey
ALTER TABLE "Branch" ADD CONSTRAINT "Branch_clinicId_fkey" FOREIGN KEY ("clinicId") REFERENCES "Clinic"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Doctor" ADD CONSTRAINT "Doctor_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Cabinet" ADD CONSTRAINT "Cabinet_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DoctorSchedule" ADD CONSTRAINT "DoctorSchedule_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DoctorTimeOff" ADD CONSTRAINT "DoctorTimeOff_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Appointment" ADD CONSTRAINT "Appointment_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ─── Stage B: backfill ────────────────────────────────────────────────────
-- gen_random_uuid() ships with Postgres 13+ in the `pgcrypto`-style core; if
-- the target cluster is older, uncomment the next line:
--   CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. Default Branch per clinic (idempotent — the (clinicId, slug) unique
--    skips re-insertion on re-run).
INSERT INTO "Branch" (id, "clinicId", slug, "nameRu", "nameUz", "isDefault", "isActive", "createdAt", "updatedAt")
SELECT gen_random_uuid()::text, c.id, 'hq', 'Главный филиал', 'Asosiy filial', true, true, NOW(), NOW()
FROM "Clinic" c
ON CONFLICT ("clinicId", slug) DO NOTHING;

-- 2. Backfill branchId on the 5 newly-extended tables. Each row gets pinned
--    to its clinic's default branch (slug='hq', isDefault=true).
UPDATE "Doctor" d
   SET "branchId" = (
     SELECT b.id FROM "Branch" b
     WHERE b."clinicId" = d."clinicId" AND b."isDefault" = true
     LIMIT 1
   )
 WHERE d."branchId" IS NULL;

UPDATE "Cabinet" c
   SET "branchId" = (
     SELECT b.id FROM "Branch" b
     WHERE b."clinicId" = c."clinicId" AND b."isDefault" = true
     LIMIT 1
   )
 WHERE c."branchId" IS NULL;

UPDATE "Appointment" a
   SET "branchId" = (
     SELECT b.id FROM "Branch" b
     WHERE b."clinicId" = a."clinicId" AND b."isDefault" = true
     LIMIT 1
   )
 WHERE a."branchId" IS NULL;

UPDATE "DoctorSchedule" s
   SET "branchId" = (
     SELECT b.id FROM "Branch" b
     WHERE b."clinicId" = s."clinicId" AND b."isDefault" = true
     LIMIT 1
   )
 WHERE s."branchId" IS NULL;

UPDATE "DoctorTimeOff" t
   SET "branchId" = (
     SELECT b.id FROM "Branch" b
     WHERE b."clinicId" = t."clinicId" AND b."isDefault" = true
     LIMIT 1
   )
 WHERE t."branchId" IS NULL;
