-- MedicalCase — episode-of-care grouping for repeat patient visits.
--
-- Stage A (auto-generated by `prisma migrate dev --create-only`):
--   - CREATE TYPE "CaseStatus"
--   - CREATE TABLE "MedicalCase"
--   - ADD COLUMN Appointment.medicalCaseId (NULLABLE) + index + FK
--   - ADD COLUMN Service.freeRepeatDays (NULLABLE) — free-repeat policy
--   - FK + indexes (per-clinic composite indexes for tenancy filtering)
--
-- Stage B (hand-appended below):
--   - For every (clinicId, patientId, doctorId) cluster of existing
--     Appointments ordered by `date`, split into groups whenever the gap
--     between consecutive visits exceeds 60 days. Each group becomes a
--     MedicalCase. Status = OPEN if last visit is within the last 90 days,
--     else RESOLVED (closedAt = last visit date). primaryDoctorId =
--     doctorId. title = 'Случай от YYYY-MM-DD'.
--   - Then UPDATE Appointment.medicalCaseId for every appointment in each
--     group.
--
-- Multi-tenancy: every backfill query partitions by clinicId, so cases are
-- never created across clinic boundaries. Idempotency: only appointments
-- with a NULL medicalCaseId are considered, so re-running after partial
-- success continues from where it stopped. The heuristic prefers
-- splitting too eagerly (>60d gap → new case) over merging — manual
-- merges via UI are easier to recover from than incorrect groupings.

-- CreateEnum
CREATE TYPE "CaseStatus" AS ENUM ('OPEN', 'RESOLVED', 'ABANDONED', 'TRANSFERRED');

-- AlterTable
ALTER TABLE "Appointment" ADD COLUMN     "medicalCaseId" TEXT;

-- AlterTable
ALTER TABLE "Service" ADD COLUMN     "freeRepeatDays" INTEGER;

-- CreateTable
CREATE TABLE "MedicalCase" (
    "id" TEXT NOT NULL,
    "clinicId" TEXT NOT NULL,
    "patientId" TEXT NOT NULL,
    "primaryDoctorId" TEXT,
    "title" TEXT NOT NULL,
    "status" "CaseStatus" NOT NULL DEFAULT 'OPEN',
    "primaryComplaint" TEXT,
    "diagnosisText" TEXT,
    "diagnosisCode" TEXT,
    "notes" TEXT,
    "openedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "closedAt" TIMESTAMP(3),
    "closedReason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "MedicalCase_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "MedicalCase_clinicId_patientId_status_idx" ON "MedicalCase"("clinicId", "patientId", "status");

-- CreateIndex
CREATE INDEX "MedicalCase_clinicId_status_openedAt_idx" ON "MedicalCase"("clinicId", "status", "openedAt");

-- CreateIndex
CREATE INDEX "MedicalCase_clinicId_primaryDoctorId_status_idx" ON "MedicalCase"("clinicId", "primaryDoctorId", "status");

-- CreateIndex
CREATE INDEX "Appointment_clinicId_medicalCaseId_idx" ON "Appointment"("clinicId", "medicalCaseId");

-- AddForeignKey
ALTER TABLE "Appointment" ADD CONSTRAINT "Appointment_medicalCaseId_fkey" FOREIGN KEY ("medicalCaseId") REFERENCES "MedicalCase"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MedicalCase" ADD CONSTRAINT "MedicalCase_clinicId_fkey" FOREIGN KEY ("clinicId") REFERENCES "Clinic"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MedicalCase" ADD CONSTRAINT "MedicalCase_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MedicalCase" ADD CONSTRAINT "MedicalCase_primaryDoctorId_fkey" FOREIGN KEY ("primaryDoctorId") REFERENCES "Doctor"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ─── Stage B: backfill MedicalCase rows from existing Appointments ────────
-- gen_random_uuid() ships with Postgres 13+ in core; for older clusters:
--   CREATE EXTENSION IF NOT EXISTS pgcrypto;
--
-- The heuristic: for each (clinicId, patientId, doctorId), order
-- appointments by date and split into a new case whenever the gap from the
-- previous visit exceeds 60 days. Each group becomes one MedicalCase.
-- Only appointments with NULL medicalCaseId are considered, so the
-- migration is safe to re-run after partial application.

WITH ordered AS (
  SELECT
    a.id            AS appt_id,
    a."clinicId"    AS clinic_id,
    a."patientId"   AS patient_id,
    a."doctorId"    AS doctor_id,
    a."date"        AS appt_date,
    LAG(a."date") OVER (
      PARTITION BY a."clinicId", a."patientId", a."doctorId"
      ORDER BY a."date", a.id
    ) AS prev_date
  FROM "Appointment" a
  WHERE a."medicalCaseId" IS NULL
),
flagged AS (
  SELECT
    appt_id,
    clinic_id,
    patient_id,
    doctor_id,
    appt_date,
    -- 1 each time we cross a >60 day gap (or for the very first visit in
    -- the partition, which has prev_date = NULL).
    CASE
      WHEN prev_date IS NULL THEN 1
      WHEN appt_date - prev_date > INTERVAL '60 days' THEN 1
      ELSE 0
    END AS is_break
  FROM ordered
),
grouped AS (
  SELECT
    appt_id,
    clinic_id,
    patient_id,
    doctor_id,
    appt_date,
    SUM(is_break) OVER (
      PARTITION BY clinic_id, patient_id, doctor_id
      ORDER BY appt_date, appt_id
      ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS group_num
  FROM flagged
),
groups AS (
  SELECT
    clinic_id,
    patient_id,
    doctor_id,
    group_num,
    MIN(appt_date) AS first_date,
    MAX(appt_date) AS last_date,
    ARRAY_AGG(appt_id) AS appt_ids
  FROM grouped
  GROUP BY clinic_id, patient_id, doctor_id, group_num
),
new_cases AS (
  INSERT INTO "MedicalCase" (
    id, "clinicId", "patientId", "primaryDoctorId",
    title, status, "openedAt", "closedAt", "createdAt", "updatedAt"
  )
  SELECT
    gen_random_uuid()::text                                  AS id,
    g.clinic_id                                              AS "clinicId",
    g.patient_id                                             AS "patientId",
    g.doctor_id                                              AS "primaryDoctorId",
    'Случай от ' || to_char(g.first_date, 'YYYY-MM-DD')      AS title,
    CASE
      WHEN g.last_date > NOW() - INTERVAL '90 days' THEN 'OPEN'::"CaseStatus"
      ELSE 'RESOLVED'::"CaseStatus"
    END                                                      AS status,
    g.first_date                                             AS "openedAt",
    CASE
      WHEN g.last_date > NOW() - INTERVAL '90 days' THEN NULL
      ELSE g.last_date
    END                                                      AS "closedAt",
    NOW()                                                    AS "createdAt",
    NOW()                                                    AS "updatedAt"
  FROM groups g
  RETURNING id, "clinicId", "patientId", "primaryDoctorId", "openedAt"
),
case_for_group AS (
  -- Re-join the freshly inserted cases back to their groups using the
  -- (clinicId, patientId, primaryDoctorId, openedAt) tuple, which is
  -- unique per group within this backfill batch.
  SELECT
    nc.id AS case_id,
    g.appt_ids
  FROM new_cases nc
  JOIN groups g
    ON  g.clinic_id  = nc."clinicId"
    AND g.patient_id = nc."patientId"
    AND g.doctor_id  IS NOT DISTINCT FROM nc."primaryDoctorId"
    AND g.first_date = nc."openedAt"
)
UPDATE "Appointment" a
   SET "medicalCaseId" = cfg.case_id
  FROM case_for_group cfg
 WHERE a.id = ANY(cfg.appt_ids)
   AND a."medicalCaseId" IS NULL;
