/**
 * Catalog extension — medications missing from `_drug-catalog.ts`.
 *
 * The neurologist reported the drug base as too thin in his first weeks. The
 * original 156 entries cover the common cases well, so this adds depth rather
 * than replacing anything: second-line and specialist drugs, and the CIS brand
 * names patients actually arrive holding.
 *
 * Weighted toward this clinic's reality — neurology first, then the
 * comorbidities a neurologist prescribes around (cardiovascular, psychiatric,
 * gastroprotection alongside NSAIDs), then general practice.
 *
 * WHAT IS DELIBERATELY ABSENT: indications, contraindications, side effects
 * and pregnancy categories. Those live in `_drug-data.ts` and must come from a
 * pharmacist or an official source — inventing them would put plausible,
 * unverified clinical text in front of a doctor, which is worse than an empty
 * field he knows to be empty.
 *
 * Doses are *suggestions* for the dosage builder — the strengths these drugs
 * are actually sold in, not a prescribing recommendation. The doctor confirms
 * every one.
 *
 * ⚠️ Review before trusting in production: this list was assembled without an
 * official registry. Availability in Uzbekistan varies, and a pharmacist
 * should confirm the ones outside routine practice.
 */
import type { Drug } from "./_drug-catalog";

export const DRUGS_EXTRA: Drug[] = [
  // ─── Неврология: эпилепсия ───────────────────────────────────────────
  {
    id: "oxcarbazepine",
    nameRu: "Окскарбазепин",
    intl: "Oxcarbazepine",
    brands: ["Трилептал", "Оксапин"],
    category: "NEUROLOGICAL",
    forms: [{ form: "TAB", doses: ["300 мг", "600 мг", "150 мг"] }],
  },
  {
    id: "phenytoin",
    nameRu: "Фенитоин",
    intl: "Phenytoin",
    brands: ["Дифенин"],
    category: "NEUROLOGICAL",
    forms: [{ form: "TAB", doses: ["100 мг"] }],
  },
  {
    id: "clonazepam",
    nameRu: "Клоназепам",
    intl: "Clonazepam",
    brands: ["Ривотрил"],
    category: "NEUROLOGICAL",
    forms: [{ form: "TAB", doses: ["0,5 мг", "2 мг"] }],
  },
  {
    id: "ethosuximide",
    nameRu: "Этосуксимид",
    intl: "Ethosuximide",
    brands: ["Суксилеп"],
    category: "NEUROLOGICAL",
    forms: [{ form: "CAP", doses: ["250 мг"] }],
  },
  {
    id: "zonisamide",
    nameRu: "Зонисамид",
    intl: "Zonisamide",
    brands: ["Зонегран"],
    category: "NEUROLOGICAL",
    forms: [{ form: "CAP", doses: ["25 мг", "50 мг", "100 мг"] }],
  },
  {
    id: "lacosamide",
    nameRu: "Лакосамид",
    intl: "Lacosamide",
    brands: ["Вимпат"],
    category: "NEUROLOGICAL",
    forms: [{ form: "TAB", doses: ["50 мг", "100 мг", "200 мг"] }],
  },

  // ─── Неврология: мигрень и головная боль ─────────────────────────────
  {
    id: "eletriptan",
    nameRu: "Элетриптан",
    intl: "Eletriptan",
    brands: ["Релпакс"],
    category: "NEUROLOGICAL",
    forms: [{ form: "TAB", doses: ["40 мг", "20 мг"] }],
  },
  {
    id: "rizatriptan",
    nameRu: "Ризатриптан",
    intl: "Rizatriptan",
    brands: ["Максалт"],
    category: "NEUROLOGICAL",
    forms: [{ form: "TAB", doses: ["10 мг", "5 мг"] }],
  },
  {
    id: "zolmitriptan",
    nameRu: "Золмитриптан",
    intl: "Zolmitriptan",
    brands: ["Зомиг"],
    category: "NEUROLOGICAL",
    forms: [{ form: "TAB", doses: ["2,5 мг"] }],
  },
  {
    id: "flunarizine",
    nameRu: "Флунаризин",
    intl: "Flunarizine",
    brands: ["Сибелиум"],
    category: "NEUROLOGICAL",
    forms: [{ form: "TAB", doses: ["5 мг", "10 мг"] }],
  },

  // ─── Неврология: нейрометаболики и нейропротекция ────────────────────
  {
    id: "cerebrolysin",
    nameRu: "Церебролизин",
    intl: "Cerebrolysin",
    brands: ["Церебролизин"],
    category: "NEUROLOGICAL",
    forms: [
      { form: "INJ_IM", doses: ["5 мл", "10 мл"] },
      { form: "INJ_IV", doses: ["10 мл", "20 мл", "30 мл"] },
    ],
  },
  {
    id: "actovegin",
    nameRu: "Актовегин",
    intl: "Deproteinised haemoderivative",
    brands: ["Актовегин"],
    category: "NEUROLOGICAL",
    forms: [
      { form: "TAB", doses: ["200 мг"] },
      { form: "INJ_IV", doses: ["5 мл (200 мг)", "10 мл (400 мг)"] },
    ],
  },
  {
    id: "cortexin",
    nameRu: "Кортексин",
    intl: "Cortexin",
    brands: ["Кортексин"],
    category: "NEUROLOGICAL",
    forms: [{ form: "INJ_IM", doses: ["10 мг", "5 мг"] }],
  },
  {
    id: "ipidacrine",
    nameRu: "Ипидакрин",
    intl: "Ipidacrine",
    brands: ["Нейромидин", "Аксамон"],
    category: "NEUROLOGICAL",
    forms: [
      { form: "TAB", doses: ["20 мг"] },
      { form: "INJ_IM", doses: ["5 мг/мл", "15 мг/мл"] },
    ],
  },
  {
    id: "choline-alfoscerate",
    nameRu: "Холина альфосцерат",
    intl: "Choline alfoscerate",
    brands: ["Глиатилин", "Церепро", "Церетон"],
    category: "NEUROLOGICAL",
    forms: [
      { form: "CAP", doses: ["400 мг"] },
      { form: "INJ_IM", doses: ["1000 мг/4 мл"] },
    ],
  },
  {
    id: "thioctic-acid",
    nameRu: "Тиоктовая (альфа-липоевая) кислота",
    intl: "Thioctic acid",
    brands: ["Тиогамма", "Берлитион", "Октолипен"],
    category: "NEUROLOGICAL",
    forms: [
      { form: "TAB", doses: ["600 мг", "300 мг"] },
      { form: "INJ_IV", doses: ["600 мг/24 мл"] },
    ],
  },
  {
    id: "ethylmethylhydroxypyridine-succinate",
    nameRu: "Этилметилгидроксипиридина сукцинат",
    intl: "Ethylmethylhydroxypyridine succinate",
    brands: ["Мексикор", "Нейрокс", "Мексиприм"],
    category: "NEUROLOGICAL",
    forms: [
      { form: "TAB", doses: ["125 мг"] },
      { form: "INJ_IV", doses: ["50 мг/мл (2 мл)", "50 мг/мл (5 мл)"] },
    ],
  },
  {
    id: "hopantenic-acid",
    nameRu: "Гопантеновая кислота",
    intl: "Hopantenic acid",
    brands: ["Пантогам", "Пантокальцин"],
    category: "NEUROLOGICAL",
    forms: [{ form: "TAB", doses: ["250 мг", "500 мг"] }],
  },
  {
    id: "aminophenylbutyric-acid",
    nameRu: "Аминофенилмасляная кислота",
    intl: "Aminophenylbutyric acid",
    brands: ["Анвифен", "Ноофен"],
    category: "NEUROLOGICAL",
    forms: [{ form: "CAP", doses: ["250 мг", "125 мг"] }],
  },
  {
    id: "meldonium",
    nameRu: "Мельдоний",
    intl: "Meldonium",
    brands: ["Милдронат", "Кардионат"],
    category: "NEUROLOGICAL",
    forms: [
      { form: "CAP", doses: ["250 мг", "500 мг"] },
      { form: "INJ_IV", doses: ["500 мг/5 мл"] },
    ],
  },

  // ─── Неврология: паркинсонизм и деменция ─────────────────────────────
  {
    id: "levodopa-carbidopa",
    nameRu: "Леводопа + Карбидопа",
    intl: "Levodopa/Carbidopa",
    brands: ["Наком", "Синдопа", "Тидомет"],
    category: "NEUROLOGICAL",
    forms: [{ form: "TAB", doses: ["250 мг/25 мг", "100 мг/25 мг"] }],
  },
  {
    id: "levodopa-benserazide",
    nameRu: "Леводопа + Бенсеразид",
    intl: "Levodopa/Benserazide",
    brands: ["Мадопар"],
    category: "NEUROLOGICAL",
    forms: [{ form: "TAB", doses: ["250 мг", "125 мг"] }],
  },
  {
    id: "amantadine",
    nameRu: "Амантадин",
    intl: "Amantadine",
    brands: ["ПК-Мерц", "Мидантан"],
    category: "NEUROLOGICAL",
    forms: [{ form: "TAB", doses: ["100 мг"] }],
  },
  {
    id: "trihexyphenidyl",
    nameRu: "Тригексифенидил",
    intl: "Trihexyphenidyl",
    brands: ["Циклодол", "Паркопан"],
    category: "NEUROLOGICAL",
    forms: [{ form: "TAB", doses: ["2 мг", "5 мг"] }],
  },
  {
    id: "rivastigmine",
    nameRu: "Ривастигмин",
    intl: "Rivastigmine",
    brands: ["Экселон", "Альценорм"],
    category: "NEUROLOGICAL",
    forms: [
      { form: "CAP", doses: ["1,5 мг", "3 мг", "4,5 мг", "6 мг"] },
      { form: "PATCH", doses: ["4,6 мг/24 ч", "9,5 мг/24 ч"] },
    ],
  },
  {
    id: "galantamine",
    nameRu: "Галантамин",
    intl: "Galantamine",
    brands: ["Реминил", "Нивалин"],
    category: "NEUROLOGICAL",
    forms: [{ form: "TAB", doses: ["4 мг", "8 мг", "12 мг"] }],
  },
  {
    id: "ropinirole",
    nameRu: "Ропинирол",
    intl: "Ropinirole",
    brands: ["Реквип"],
    category: "NEUROLOGICAL",
    forms: [{ form: "TAB", doses: ["0,25 мг", "1 мг", "2 мг"] }],
  },

  // ─── Неврология: головокружение, сосудистые ──────────────────────────
  {
    id: "dimenhydrinate",
    nameRu: "Дименгидринат",
    intl: "Dimenhydrinate",
    brands: ["Драмина", "Авиамарин"],
    category: "NEUROLOGICAL",
    forms: [{ form: "TAB", doses: ["50 мг"] }],
  },
  {
    id: "ginkgo-biloba",
    nameRu: "Гинкго билоба",
    intl: "Ginkgo biloba extract",
    brands: ["Танакан", "Билобил", "Мемоплант"],
    category: "NEUROLOGICAL",
    forms: [{ form: "TAB", doses: ["40 мг", "80 мг", "120 мг"] }],
  },
  {
    id: "dipyridamole",
    nameRu: "Дипиридамол",
    intl: "Dipyridamole",
    brands: ["Курантил"],
    category: "NEUROLOGICAL",
    forms: [{ form: "TAB", doses: ["25 мг", "75 мг"] }],
  },

  // ─── Миорелаксанты и нейропатическая боль ────────────────────────────
  {
    id: "thiocolchicoside",
    nameRu: "Тиоколхикозид",
    intl: "Thiocolchicoside",
    brands: ["Мускомед", "Миорикс"],
    category: "NEUROLOGICAL",
    forms: [
      { form: "CAP", doses: ["4 мг", "8 мг"] },
      { form: "INJ_IM", doses: ["4 мг/2 мл"] },
    ],
  },
  {
    id: "orphenadrine",
    nameRu: "Орфенадрин",
    intl: "Orphenadrine",
    brands: ["Норфлекс"],
    category: "NEUROLOGICAL",
    forms: [{ form: "INJ_IM", doses: ["30 мг/мл"] }],
  },

  // ─── Психиатрия ──────────────────────────────────────────────────────
  {
    id: "fluoxetine",
    nameRu: "Флуоксетин",
    intl: "Fluoxetine",
    brands: ["Прозак", "Флуоксетин"],
    category: "PSYCHIATRIC",
    forms: [{ form: "CAP", doses: ["20 мг"] }],
  },
  {
    id: "paroxetine",
    nameRu: "Пароксетин",
    intl: "Paroxetine",
    brands: ["Паксил", "Рексетин"],
    category: "PSYCHIATRIC",
    forms: [{ form: "TAB", doses: ["20 мг", "30 мг"] }],
  },
  {
    id: "fluvoxamine",
    nameRu: "Флувоксамин",
    intl: "Fluvoxamine",
    brands: ["Феварин"],
    category: "PSYCHIATRIC",
    forms: [{ form: "TAB", doses: ["50 мг", "100 мг"] }],
  },
  {
    id: "mirtazapine",
    nameRu: "Миртазапин",
    intl: "Mirtazapine",
    brands: ["Ремерон", "Каликста"],
    category: "PSYCHIATRIC",
    forms: [{ form: "TAB", doses: ["15 мг", "30 мг"] }],
  },
  {
    id: "trazodone",
    nameRu: "Тразодон",
    intl: "Trazodone",
    brands: ["Триттико"],
    category: "PSYCHIATRIC",
    forms: [{ form: "TAB", doses: ["150 мг", "75 мг"] }],
  },
  {
    id: "agomelatine",
    nameRu: "Агомелатин",
    intl: "Agomelatine",
    brands: ["Вальдоксан"],
    category: "PSYCHIATRIC",
    forms: [{ form: "TAB", doses: ["25 мг"] }],
  },
  {
    id: "quetiapine",
    nameRu: "Кветиапин",
    intl: "Quetiapine",
    brands: ["Сероквель", "Кветиапин"],
    category: "PSYCHIATRIC",
    forms: [{ form: "TAB", doses: ["25 мг", "100 мг", "200 мг"] }],
  },
  {
    id: "risperidone",
    nameRu: "Рисперидон",
    intl: "Risperidone",
    brands: ["Рисполепт", "Риссет"],
    category: "PSYCHIATRIC",
    forms: [{ form: "TAB", doses: ["1 мг", "2 мг", "4 мг"] }],
  },
  {
    id: "olanzapine",
    nameRu: "Оланзапин",
    intl: "Olanzapine",
    brands: ["Зипрекса", "Эголанза"],
    category: "PSYCHIATRIC",
    forms: [{ form: "TAB", doses: ["5 мг", "10 мг"] }],
  },
  {
    id: "haloperidol",
    nameRu: "Галоперидол",
    intl: "Haloperidol",
    brands: ["Галоперидол"],
    category: "PSYCHIATRIC",
    forms: [
      { form: "TAB", doses: ["1,5 мг", "5 мг"] },
      { form: "INJ_IM", doses: ["5 мг/мл"] },
    ],
  },
  {
    id: "chlorprothixene",
    nameRu: "Хлорпротиксен",
    intl: "Chlorprothixene",
    brands: ["Труксал"],
    category: "PSYCHIATRIC",
    forms: [{ form: "TAB", doses: ["15 мг", "50 мг"] }],
  },
  {
    id: "buspirone",
    nameRu: "Буспирон",
    intl: "Buspirone",
    brands: ["Спитомин"],
    category: "PSYCHIATRIC",
    forms: [{ form: "TAB", doses: ["5 мг", "10 мг"] }],
  },
  {
    id: "zopiclone",
    nameRu: "Зопиклон",
    intl: "Zopiclone",
    brands: ["Сомнол", "Имован"],
    category: "SEDATIVE",
    forms: [{ form: "TAB", doses: ["7,5 мг"] }],
  },
  {
    id: "zolpidem",
    nameRu: "Золпидем",
    intl: "Zolpidem",
    brands: ["Санвал", "Ивадал"],
    category: "SEDATIVE",
    forms: [{ form: "TAB", doses: ["10 мг"] }],
  },
  {
    id: "valerian",
    nameRu: "Валерианы экстракт",
    intl: "Valerian extract",
    brands: ["Валериана"],
    category: "SEDATIVE",
    forms: [{ form: "TAB", doses: ["20 мг", "200 мг"] }],
  },

  // ─── Кардиология ─────────────────────────────────────────────────────
  {
    id: "carvedilol",
    nameRu: "Карведилол",
    intl: "Carvedilol",
    brands: ["Дилатренд", "Кориол"],
    category: "CARDIO",
    forms: [{ form: "TAB", doses: ["6,25 мг", "12,5 мг", "25 мг"] }],
  },
  {
    id: "verapamil",
    nameRu: "Верапамил",
    intl: "Verapamil",
    brands: ["Изоптин", "Финоптин"],
    category: "CARDIO",
    forms: [{ form: "TAB", doses: ["40 мг", "80 мг", "240 мг (ретард)"] }],
  },
  {
    id: "diltiazem",
    nameRu: "Дилтиазем",
    intl: "Diltiazem",
    brands: ["Кардил", "Дилзем"],
    category: "CARDIO",
    forms: [{ form: "TAB", doses: ["60 мг", "90 мг"] }],
  },
  {
    id: "telmisartan",
    nameRu: "Телмисартан",
    intl: "Telmisartan",
    brands: ["Микардис", "Телзап"],
    category: "CARDIO",
    forms: [{ form: "TAB", doses: ["40 мг", "80 мг"] }],
  },
  {
    id: "irbesartan",
    nameRu: "Ирбесартан",
    intl: "Irbesartan",
    brands: ["Апровель"],
    category: "CARDIO",
    forms: [{ form: "TAB", doses: ["150 мг", "300 мг"] }],
  },
  {
    id: "perindopril",
    nameRu: "Периндоприл",
    intl: "Perindopril",
    brands: ["Престариум", "Перинева"],
    category: "CARDIO",
    forms: [{ form: "TAB", doses: ["4 мг", "8 мг", "5 мг", "10 мг"] }],
  },
  {
    id: "torasemide",
    nameRu: "Торасемид",
    intl: "Torasemide",
    brands: ["Диувер", "Тригрим"],
    category: "DIURETIC",
    forms: [{ form: "TAB", doses: ["5 мг", "10 мг"] }],
  },
  {
    id: "hydrochlorothiazide",
    nameRu: "Гидрохлортиазид",
    intl: "Hydrochlorothiazide",
    brands: ["Гипотиазид"],
    category: "DIURETIC",
    forms: [{ form: "TAB", doses: ["25 мг", "100 мг"] }],
  },
  {
    id: "ivabradine",
    nameRu: "Ивабрадин",
    intl: "Ivabradine",
    brands: ["Кораксан"],
    category: "CARDIO",
    forms: [{ form: "TAB", doses: ["5 мг", "7,5 мг"] }],
  },
  {
    id: "trimetazidine",
    nameRu: "Триметазидин",
    intl: "Trimetazidine",
    brands: ["Предуктал", "Депренорм"],
    category: "CARDIO",
    forms: [{ form: "TAB", doses: ["35 мг (МВ)", "20 мг"] }],
  },
  {
    id: "isosorbide-mononitrate",
    nameRu: "Изосорбида мононитрат",
    intl: "Isosorbide mononitrate",
    brands: ["Моночинкве", "Эфокс"],
    category: "CARDIO",
    forms: [{ form: "TAB", doses: ["20 мг", "40 мг"] }],
  },
  {
    id: "digoxin",
    nameRu: "Дигоксин",
    intl: "Digoxin",
    brands: ["Дигоксин"],
    category: "CARDIO",
    forms: [{ form: "TAB", doses: ["0,25 мг"] }],
  },
  {
    id: "apixaban",
    nameRu: "Апиксабан",
    intl: "Apixaban",
    brands: ["Эликвис"],
    category: "CARDIO",
    forms: [{ form: "TAB", doses: ["2,5 мг", "5 мг"] }],
  },
  {
    id: "dabigatran",
    nameRu: "Дабигатран",
    intl: "Dabigatran",
    brands: ["Прадакса"],
    category: "CARDIO",
    forms: [{ form: "CAP", doses: ["110 мг", "150 мг"] }],
  },
  {
    id: "simvastatin",
    nameRu: "Симвастатин",
    intl: "Simvastatin",
    brands: ["Зокор", "Вазилип"],
    category: "CARDIO",
    forms: [{ form: "TAB", doses: ["10 мг", "20 мг", "40 мг"] }],
  },
  {
    id: "fenofibrate",
    nameRu: "Фенофибрат",
    intl: "Fenofibrate",
    brands: ["Трайкор"],
    category: "CARDIO",
    forms: [{ form: "TAB", doses: ["145 мг"] }],
  },
  {
    id: "ezetimibe",
    nameRu: "Эзетимиб",
    intl: "Ezetimibe",
    brands: ["Эзетрол"],
    category: "CARDIO",
    forms: [{ form: "TAB", doses: ["10 мг"] }],
  },
  {
    id: "moxonidine",
    nameRu: "Моксонидин",
    intl: "Moxonidine",
    brands: ["Физиотенз", "Моксарел"],
    category: "CARDIO",
    forms: [{ form: "TAB", doses: ["0,2 мг", "0,4 мг"] }],
  },

  // ─── НПВС и анальгетики ──────────────────────────────────────────────
  {
    id: "dexketoprofen",
    nameRu: "Декскетопрофен",
    intl: "Dexketoprofen",
    brands: ["Дексалгин", "Фламадекс"],
    category: "NSAID",
    forms: [
      { form: "TAB", doses: ["25 мг"] },
      { form: "INJ_IM", doses: ["50 мг/2 мл"] },
    ],
  },
  {
    id: "lornoxicam",
    nameRu: "Лорноксикам",
    intl: "Lornoxicam",
    brands: ["Ксефокам"],
    category: "NSAID",
    forms: [
      { form: "TAB", doses: ["8 мг", "4 мг"] },
      { form: "INJ_IM", doses: ["8 мг"] },
    ],
  },
  {
    id: "etoricoxib",
    nameRu: "Эторикоксиб",
    intl: "Etoricoxib",
    brands: ["Аркоксиа"],
    category: "NSAID",
    forms: [{ form: "TAB", doses: ["60 мг", "90 мг", "120 мг"] }],
  },
  {
    id: "aceclofenac",
    nameRu: "Ацеклофенак",
    intl: "Aceclofenac",
    brands: ["Аэртал"],
    category: "NSAID",
    forms: [{ form: "TAB", doses: ["100 мг"] }],
  },
  {
    id: "piroxicam",
    nameRu: "Пироксикам",
    intl: "Piroxicam",
    brands: ["Пироксикам"],
    category: "NSAID",
    forms: [{ form: "CAP", doses: ["10 мг", "20 мг"] }],
  },
  {
    id: "flupirtine",
    nameRu: "Флупиртин",
    intl: "Flupirtine",
    brands: ["Катадолон"],
    category: "ANALGESIC",
    forms: [{ form: "CAP", doses: ["100 мг"] }],
  },

  // ─── ЖКТ ─────────────────────────────────────────────────────────────
  {
    id: "esomeprazole",
    nameRu: "Эзомепразол",
    intl: "Esomeprazole",
    brands: ["Нексиум", "Эманера"],
    category: "GI",
    forms: [{ form: "CAP", doses: ["20 мг", "40 мг"] }],
  },
  {
    id: "lansoprazole",
    nameRu: "Лансопразол",
    intl: "Lansoprazole",
    brands: ["Ланзап", "Эпикур"],
    category: "GI",
    forms: [{ form: "CAP", doses: ["15 мг", "30 мг"] }],
  },
  {
    id: "itopride",
    nameRu: "Итоприд",
    intl: "Itopride",
    brands: ["Ганатон", "Итомед"],
    category: "GI",
    forms: [{ form: "TAB", doses: ["50 мг"] }],
  },
  {
    id: "trimebutine",
    nameRu: "Тримебутин",
    intl: "Trimebutine",
    brands: ["Тримедат"],
    category: "GI",
    forms: [{ form: "TAB", doses: ["100 мг", "200 мг"] }],
  },
  {
    id: "rifaximin",
    nameRu: "Рифаксимин",
    intl: "Rifaximin",
    brands: ["Альфа Нормикс"],
    category: "GI",
    forms: [{ form: "TAB", doses: ["200 мг"] }],
  },
  {
    id: "mesalazine",
    nameRu: "Месалазин",
    intl: "Mesalazine",
    brands: ["Салофальк", "Пентаса"],
    category: "GI",
    forms: [{ form: "TAB", doses: ["500 мг", "1000 мг"] }],
  },
  {
    id: "ademetionine",
    nameRu: "Адеметионин",
    intl: "Ademetionine",
    brands: ["Гептрал", "Гепторал"],
    category: "GI",
    forms: [
      { form: "TAB", doses: ["400 мг"] },
      { form: "INJ_IV", doses: ["400 мг"] },
    ],
  },
  {
    id: "essential-phospholipids",
    nameRu: "Фосфолипиды эссенциальные",
    intl: "Essential phospholipids",
    brands: ["Эссенциале форте Н", "Эссливер"],
    category: "GI",
    forms: [{ form: "CAP", doses: ["300 мг"] }],
  },
  {
    id: "silymarin",
    nameRu: "Силимарин",
    intl: "Silymarin",
    brands: ["Карсил", "Легалон"],
    category: "GI",
    forms: [{ form: "TAB", doses: ["35 мг", "140 мг"] }],
  },
  {
    id: "macrogol",
    nameRu: "Макрогол",
    intl: "Macrogol",
    brands: ["Форлакс", "Транзипег"],
    category: "GI",
    forms: [{ form: "POWDER", doses: ["10 г", "4 г"] }],
  },
  {
    id: "bisacodyl",
    nameRu: "Бисакодил",
    intl: "Bisacodyl",
    brands: ["Дульколакс"],
    category: "GI",
    forms: [
      { form: "TAB", doses: ["5 мг"] },
      { form: "SUPP_RECT", doses: ["10 мг"] },
    ],
  },

  // ─── Антибиотики и противомикробные ──────────────────────────────────
  {
    id: "ampicillin",
    nameRu: "Ампициллин",
    intl: "Ampicillin",
    brands: ["Ампициллин"],
    category: "ANTIBIOTIC",
    forms: [
      { form: "TAB", doses: ["250 мг", "500 мг"] },
      { form: "INJ_IM", doses: ["500 мг", "1 г"] },
    ],
  },
  {
    id: "cephalexin",
    nameRu: "Цефалексин",
    intl: "Cefalexin",
    brands: ["Цефалексин"],
    category: "ANTIBIOTIC",
    forms: [{ form: "CAP", doses: ["250 мг", "500 мг"] }],
  },
  {
    id: "ceftazidime",
    nameRu: "Цефтазидим",
    intl: "Ceftazidime",
    brands: ["Фортум"],
    category: "ANTIBIOTIC",
    forms: [{ form: "INJ_IV", doses: ["1 г", "2 г"] }],
  },
  {
    id: "cefepime",
    nameRu: "Цефепим",
    intl: "Cefepime",
    brands: ["Максипим"],
    category: "ANTIBIOTIC",
    forms: [{ form: "INJ_IV", doses: ["1 г", "2 г"] }],
  },
  {
    id: "meropenem",
    nameRu: "Меропенем",
    intl: "Meropenem",
    brands: ["Меронем"],
    category: "ANTIBIOTIC",
    forms: [{ form: "INJ_IV", doses: ["500 мг", "1 г"] }],
  },
  {
    id: "vancomycin",
    nameRu: "Ванкомицин",
    intl: "Vancomycin",
    brands: ["Ванкомицин"],
    category: "ANTIBIOTIC",
    forms: [{ form: "INJ_IV", doses: ["500 мг", "1 г"] }],
  },
  {
    id: "linezolid",
    nameRu: "Линезолид",
    intl: "Linezolid",
    brands: ["Зивокс"],
    category: "ANTIBIOTIC",
    forms: [{ form: "TAB", doses: ["600 мг"] }],
  },
  {
    id: "josamycin",
    nameRu: "Джозамицин",
    intl: "Josamycin",
    brands: ["Вильпрафен"],
    category: "ANTIBIOTIC",
    forms: [{ form: "TAB", doses: ["500 мг", "1000 мг"] }],
  },
  {
    id: "sultamicillin",
    nameRu: "Сультамициллин",
    intl: "Sultamicillin",
    brands: ["Уназин"],
    category: "ANTIBIOTIC",
    forms: [{ form: "TAB", doses: ["375 мг"] }],
  },
  {
    id: "clindamycin",
    nameRu: "Клиндамицин",
    intl: "Clindamycin",
    brands: ["Далацин", "Клиндацин"],
    category: "ANTIBIOTIC",
    forms: [
      { form: "CAP", doses: ["150 мг", "300 мг"] },
      { form: "INJ_IM", doses: ["300 мг/2 мл"] },
    ],
  },

  // ─── Эндокринология ──────────────────────────────────────────────────
  {
    id: "glimepiride",
    nameRu: "Глимепирид",
    intl: "Glimepiride",
    brands: ["Амарил", "Диамерид"],
    category: "ENDOCRINE",
    forms: [{ form: "TAB", doses: ["1 мг", "2 мг", "3 мг", "4 мг"] }],
  },
  {
    id: "empagliflozin",
    nameRu: "Эмпаглифлозин",
    intl: "Empagliflozin",
    brands: ["Джардинс"],
    category: "ENDOCRINE",
    forms: [{ form: "TAB", doses: ["10 мг", "25 мг"] }],
  },
  {
    id: "dapagliflozin",
    nameRu: "Дапаглифлозин",
    intl: "Dapagliflozin",
    brands: ["Форсига"],
    category: "ENDOCRINE",
    forms: [{ form: "TAB", doses: ["5 мг", "10 мг"] }],
  },
  {
    id: "vildagliptin",
    nameRu: "Вилдаглиптин",
    intl: "Vildagliptin",
    brands: ["Галвус"],
    category: "ENDOCRINE",
    forms: [{ form: "TAB", doses: ["50 мг"] }],
  },
  {
    id: "insulin-glargine",
    nameRu: "Инсулин гларгин",
    intl: "Insulin glargine",
    brands: ["Лантус", "Туджео"],
    category: "ENDOCRINE",
    forms: [{ form: "INJ_SC", doses: ["100 ЕД/мл"] }],
  },
  {
    id: "insulin-aspart",
    nameRu: "Инсулин аспарт",
    intl: "Insulin aspart",
    brands: ["НовоРапид"],
    category: "ENDOCRINE",
    forms: [{ form: "INJ_SC", doses: ["100 ЕД/мл"] }],
  },
  {
    id: "colecalciferol",
    nameRu: "Колекальциферол (витамин D3)",
    intl: "Colecalciferol",
    brands: ["Аквадетрим", "Вигантол"],
    category: "VITAMIN",
    forms: [
      { form: "DROPS_ORAL", doses: ["15 000 МЕ/мл"] },
      { form: "TAB", doses: ["2000 МЕ", "5000 МЕ"] },
    ],
  },
  {
    id: "alendronic-acid",
    nameRu: "Алендроновая кислота",
    intl: "Alendronic acid",
    brands: ["Фосамакс", "Осталон"],
    category: "ENDOCRINE",
    forms: [{ form: "TAB", doses: ["70 мг"] }],
  },

  // ─── Витамины и минералы ─────────────────────────────────────────────
  {
    id: "magnesium-b6",
    nameRu: "Магния лактат + Пиридоксин",
    intl: "Magnesium lactate/Pyridoxine",
    brands: ["Магне B6", "Магнелис B6"],
    category: "VITAMIN",
    forms: [{ form: "TAB", doses: ["470 мг/5 мг"] }],
  },
  {
    id: "folic-acid",
    nameRu: "Фолиевая кислота",
    intl: "Folic acid",
    brands: ["Фолиевая кислота"],
    category: "VITAMIN",
    forms: [{ form: "TAB", doses: ["1 мг", "5 мг"] }],
  },
  {
    id: "ferrous-sulfate",
    nameRu: "Железа сульфат",
    intl: "Ferrous sulfate",
    brands: ["Сорбифер Дурулес", "Тардиферон"],
    category: "VITAMIN",
    forms: [{ form: "TAB", doses: ["320 мг (100 мг Fe)"] }],
  },
  {
    id: "ferric-hydroxide-polymaltose",
    nameRu: "Железа гидроксид полимальтозат",
    intl: "Ferric hydroxide polymaltose",
    brands: ["Мальтофер", "Феррум Лек"],
    category: "VITAMIN",
    forms: [
      { form: "TAB", doses: ["100 мг"] },
      { form: "SYRUP", doses: ["50 мг/5 мл"] },
    ],
  },
  {
    id: "potassium-magnesium-asparaginate",
    nameRu: "Калия и магния аспарагинат",
    intl: "Potassium/Magnesium aspartate",
    brands: ["Панангин", "Аспаркам"],
    category: "VITAMIN",
    forms: [{ form: "TAB", doses: ["158 мг/140 мг"] }],
  },
  {
    id: "pyridoxine",
    nameRu: "Пиридоксин (витамин B6)",
    intl: "Pyridoxine",
    brands: ["Пиридоксин"],
    category: "VITAMIN",
    forms: [{ form: "INJ_IM", doses: ["50 мг/мл"] }],
  },
  {
    id: "thiamine",
    nameRu: "Тиамин (витамин B1)",
    intl: "Thiamine",
    brands: ["Тиамин"],
    category: "VITAMIN",
    forms: [{ form: "INJ_IM", doses: ["50 мг/мл"] }],
  },

  // ─── Прочее общей практики ───────────────────────────────────────────
  {
    id: "betahistine-24",
    nameRu: "Бетагистин (24 мг)",
    intl: "Betahistine",
    brands: ["Бетасерк", "Вестибо"],
    category: "NEUROLOGICAL",
    forms: [{ form: "TAB", doses: ["24 мг", "16 мг", "8 мг"] }],
  },
  {
    id: "diosmin-hesperidin",
    nameRu: "Диосмин + Гесперидин",
    intl: "Diosmin/Hesperidin",
    brands: ["Детралекс", "Венарус"],
    category: "CARDIO",
    forms: [{ form: "TAB", doses: ["500 мг", "1000 мг"] }],
  },
  {
    id: "ketotifen",
    nameRu: "Кетотифен",
    intl: "Ketotifen",
    brands: ["Задитен"],
    category: "ANTIHISTAMINE",
    forms: [{ form: "TAB", doses: ["1 мг"] }],
  },
  {
    id: "ebastine",
    nameRu: "Эбастин",
    intl: "Ebastine",
    brands: ["Кестин"],
    category: "ANTIHISTAMINE",
    forms: [{ form: "TAB", doses: ["10 мг", "20 мг"] }],
  },
  {
    id: "rupatadine",
    nameRu: "Рупатадин",
    intl: "Rupatadine",
    brands: ["Рупафин"],
    category: "ANTIHISTAMINE",
    forms: [{ form: "TAB", doses: ["10 мг"] }],
  },
  {
    id: "tizanidine-mr",
    nameRu: "Тизанидин (модиф. высвобождение)",
    intl: "Tizanidine MR",
    brands: ["Сирдалуд МР"],
    category: "NEUROLOGICAL",
    forms: [{ form: "CAP", doses: ["6 мг"] }],
  },
  {
    id: "nimodipine",
    nameRu: "Нимодипин",
    intl: "Nimodipine",
    brands: ["Нимотоп"],
    category: "NEUROLOGICAL",
    forms: [{ form: "TAB", doses: ["30 мг"] }],
  },
  {
    id: "sumatriptan-inj",
    nameRu: "Суматриптан (инъекционный)",
    intl: "Sumatriptan",
    brands: ["Имигран"],
    category: "NEUROLOGICAL",
    forms: [{ form: "INJ_SC", doses: ["6 мг/0,5 мл"] }],
  },
];
