/**
 * Emits a self-contained SQL script that re-seeds DoctorPreset rows for every
 * doctor matched by Russian specialization keywords. Designed for production
 * where the standalone Next image has no Prisma client / tsx available.
 *
 * Usage:
 *   npx tsx prisma/seed-presets-sql.ts > /tmp/seed-presets.sql
 *
 * Then on the VPS:
 *   docker exec -i medbook-postgres-1 psql -U medbook -d medbook < /tmp/seed-presets.sql
 *
 * Matching is by `Doctor.specializationRu` ILIKE patterns:
 *   - %невролог%   → neurologist preset bundle
 *   - %кардиолог%  → cardiologist preset bundle
 *
 * Additive (audit G2-05): only doctors with NO presets yet get the bundle.
 * It used to DELETE every matching doctor's presets first, and a doctor's
 * chips are their own work (built in /doctor/settings): one run would erase the
 * neurologist's whole set on the live clinic. A doctor who already has chips
 * is left alone; re-running is a no-op. The target list is taken once, before
 * the first INSERT, so a bundle is never half-applied to anyone.
 *
 * IDs are gen_random_uuid() (works on pg ≥13 with pgcrypto, which Prisma
 * extensions already enable on this DB).
 */
import { PRESETS_BY_SLUG } from "./_preset-data";

function esc(s: string) {
  return s.replace(/'/g, "''");
}

function nullable(s: string | null | undefined) {
  if (s == null) return "NULL";
  return `'${esc(s)}'`;
}

type SpecMatch = { pattern: string; bundle: keyof typeof PRESETS_BY_SLUG };

const MATCHES: SpecMatch[] = [
  { pattern: "%невролог%", bundle: "neurologist" },
  { pattern: "%кардиолог%", bundle: "cardiologist" },
];

console.log("-- Auto-generated by prisma/seed-presets-sql.ts");
console.log("-- Seeds DoctorPreset rows for matching doctors that have none yet.");
console.log("BEGIN;");

for (const { pattern, bundle } of MATCHES) {
  const presets = PRESETS_BY_SLUG[bundle];
  if (!presets) continue;

  // Doctors of this specialization without a single preset, captured before
  // the first INSERT (after it, every target would already «have presets»).
  const targets = `_preset_targets_${bundle}`;
  console.log(`-- ── ${bundle} (${pattern}) ──────────────────────────────`);
  console.log(`CREATE TEMP TABLE ${targets} ON COMMIT DROP AS`);
  console.log(`  SELECT d.id, d."clinicId" FROM "Doctor" d`);
  console.log(`  WHERE d."specializationRu" ILIKE '${pattern}'`);
  console.log(
    `    AND NOT EXISTS (SELECT 1 FROM "DoctorPreset" p WHERE p."doctorId" = d.id);`,
  );

  for (let i = 0; i < presets.length; i++) {
    const p = presets[i]!;
    const fieldValue = p.fieldValue ?? p.label;
    console.log(
      `INSERT INTO "DoctorPreset" ` +
        `("id", "clinicId", "doctorId", "field", "label", "fieldValue", "noteTemplate", "sortOrder", "active", "createdAt", "updatedAt") ` +
        `SELECT gen_random_uuid()::text, "clinicId", id, '${p.field}', '${esc(p.label)}', '${esc(fieldValue)}', ${nullable(p.noteTemplate)}, ${i}, TRUE, NOW(), NOW() ` +
        `FROM ${targets};`,
    );
  }
}

console.log("COMMIT;");
console.log("-- Summary:");
console.log(
  `SELECT "specializationRu", COUNT(*) FROM "DoctorPreset" p JOIN "Doctor" d ON d.id = p."doctorId" GROUP BY 1 ORDER BY 1;`,
);
