-- Phase 9b — Plans + Subscriptions schema + seed of canonical tiers.
--
-- Stage A (auto-generated by `prisma migrate dev --create-only`):
--   - CREATE TYPE "SubscriptionStatus"
--   - CREATE TABLE "Plan", "Subscription"
--   - FK + indexes (incl. UNIQUE on Subscription.clinicId)
--
-- Stage B (hand-appended below):
--   - Seed three canonical plans (basic / pro / enterprise) with feature
--     payloads matching `getFeatureFlags`. Idempotent via the unique slug.
--   - Backfill: every existing Clinic gets a TRIAL subscription on `pro`
--     (the most generous tier — admins downgrade later via the billing UI
--     in Phase 9c). 30-day trial. Skipped if the clinic already has one.
--
-- Same `gen_random_uuid()::text` strategy as the Phase 9a backfill — works
-- on Postgres 13+ out of the box.

-- CreateEnum
CREATE TYPE "SubscriptionStatus" AS ENUM ('TRIAL', 'ACTIVE', 'PAST_DUE', 'CANCELLED');

-- CreateTable
CREATE TABLE "Plan" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "nameRu" TEXT NOT NULL,
    "nameUz" TEXT NOT NULL,
    "priceMonth" DECIMAL(12,2) NOT NULL,
    "currency" "Currency" NOT NULL DEFAULT 'UZS',
    "features" JSONB NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Plan_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Subscription" (
    "id" TEXT NOT NULL,
    "clinicId" TEXT NOT NULL,
    "planId" TEXT NOT NULL,
    "status" "SubscriptionStatus" NOT NULL DEFAULT 'TRIAL',
    "trialEndsAt" TIMESTAMP(3),
    "currentPeriodEndsAt" TIMESTAMP(3),
    "cancelledAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Subscription_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Plan_slug_key" ON "Plan"("slug");

-- CreateIndex
CREATE INDEX "Plan_isActive_sortOrder_idx" ON "Plan"("isActive", "sortOrder");

-- CreateIndex
CREATE UNIQUE INDEX "Subscription_clinicId_key" ON "Subscription"("clinicId");

-- CreateIndex
CREATE INDEX "Subscription_status_idx" ON "Subscription"("status");

-- CreateIndex
CREATE INDEX "Subscription_currentPeriodEndsAt_idx" ON "Subscription"("currentPeriodEndsAt");

-- AddForeignKey
ALTER TABLE "Subscription" ADD CONSTRAINT "Subscription_clinicId_fkey" FOREIGN KEY ("clinicId") REFERENCES "Clinic"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Subscription" ADD CONSTRAINT "Subscription_planId_fkey" FOREIGN KEY ("planId") REFERENCES "Plan"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- ─── Stage B: seed canonical plans + backfill subscriptions ──────────────
-- gen_random_uuid() ships with Postgres 13+ in core; for older clusters:
--   CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. Seed three canonical plans. Idempotent via the unique slug.
INSERT INTO "Plan" (id, slug, "nameRu", "nameUz", "priceMonth", currency, features, "isActive", "sortOrder", "createdAt", "updatedAt") VALUES
  (gen_random_uuid()::text, 'basic',      'Basic',      'Basic',      0,        'UZS', '{"hasTelegramInbox":false,"hasCallCenter":false,"hasAnalyticsPro":false,"maxBranches":1,"maxUsers":5}'::jsonb,   true, 1, NOW(), NOW()),
  (gen_random_uuid()::text, 'pro',        'Pro',        'Pro',        1500000,  'UZS', '{"hasTelegramInbox":true,"hasCallCenter":true,"hasAnalyticsPro":false,"maxBranches":3,"maxUsers":20}'::jsonb,    true, 2, NOW(), NOW()),
  (gen_random_uuid()::text, 'enterprise', 'Enterprise', 'Enterprise', 5000000,  'UZS', '{"hasTelegramInbox":true,"hasCallCenter":true,"hasAnalyticsPro":true,"maxBranches":50,"maxUsers":500}'::jsonb,  true, 3, NOW(), NOW())
ON CONFLICT (slug) DO NOTHING;

-- 2. Give every existing clinic a TRIAL on `pro` (most generous; admins
--    downgrade later via the Phase 9c billing UI). 30-day trial. Skipped
--    if the clinic already has a subscription (re-runs are no-ops).
INSERT INTO "Subscription" (id, "clinicId", "planId", status, "trialEndsAt", "createdAt", "updatedAt")
SELECT
  gen_random_uuid()::text,
  c.id,
  (SELECT p.id FROM "Plan" p WHERE p.slug = 'pro' LIMIT 1),
  'TRIAL'::"SubscriptionStatus",
  NOW() + INTERVAL '30 days',
  NOW(),
  NOW()
FROM "Clinic" c
WHERE NOT EXISTS (SELECT 1 FROM "Subscription" s WHERE s."clinicId" = c.id);
